feat: new metric to add exporter version
mehdy/keepalived-exporter pull request #112
Opened 2023-04-05 18:17 UTC by dmachard

This PR add a new metric to follow up the version of this exporter.
No breaking changes.

2023-04-15 10:39 UTC, mehdy submitted a review, later dismissed
LGTM.
@clwluvw anything to add?

2023-04-15 13:00 UTC, clwluvw requested changes
We discussed that internally, it'd be better to switch this version handling in another package so we don't need to pass these as an arg, and would also be cleaner. Normally we can use https://github.com/prometheus/common/tree/main/version for that which has also a function to register it as a metric.

Would it be possible for you to do this change?
You can also pick this https://github.com/prometheus/node_exporter/blob/master/node_exporter.go#L122 as an example.

2023-04-18 19:49 UTC, dmachard commented
Thank for the tip, you are right it's more cleaner.
Below the new metrics with prometheus version package.

```
# HELP keepalived_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which keepalived_exporter was built.
keepalived_exporter_build_info{branch="",goversion="go1.18.1",revision="",version="689046e"} 1
```

2023-04-18 20:31 UTC, clwluvw requested changes

2023-04-18 20:31 UTC, clwluvw commented on cmd/keepalived-exporter/main.go
> +	promver.Version = version
Thanks! Just two things are remaining to get it done.
1. Please remove the vars (`version`, `commit`, `buildTime`) from the main package and edit the Makefile to set directly to the `prometheus/common/version` package vars.
2. Please edit the Makefile to set `branch` and `revision` as well (Let's not expose a metric with empty labels).

2023-04-19 06:46 UTC, dmachard commented
done,   updated output version:

```
$ ./keepalived-exporter -version
INFO[0000] Keepalived Exporter                           build_time="2023-04-19_08:43:43_+0200" commit=9c200ce version=9c200ce
```

```
# HELP keepalived_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which keepalived_exporter was built.
keepalived_exporter_build_info{branch="feat-add-version",goversion="go1.18.1",revision="9c200ce",version="9c200ce"} 1
```

2023-04-19 20:19 UTC, clwluvw approved these changes
LGTM! Thanks!

2023-04-19 20:20 UTC, merged